### ISSUE TITLE
Check that all examples in API work

### ISSUE THREAD

**Issue by zuphilip** [infolis/infolis-web#20]
All the examples in http://infolis.gesis.org/infolink/api should work, i.e. return a `200` or similar code. (I will not test the DELETE actions:)

**Comment by zuphilip** [comment]
```
$ curl -X GET --header "Accept: text/n3" "http://infolis.gesis.org/infolink/api
/execution"
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>502 Proxy Error</title>
</head><body>
<h1>Proxy Error</h1>
<p>The proxy server received an invalid
response from an upstream server.<br />
The proxy server could not handle the request <em><a href="/infolink/api/executi
on">GET&nbsp;/infolink/api/execution</a></em>.<p>
Reason: <strong>Error reading from remote server</strong></p></p>
<hr>
<address>Apache/2.4.7 (Ubuntu) Server at infolis.gesis.org Port 80</address>
</body></html>
```

**Comment by zuphilip** [comment]
The example in [post /api/execution](http://infolis.gesis.org/infolink/api#!/rest-ld-execution/post_api_execution) throws an error:

``` js
{
  "stack": "Error: ValidationError: Path `status` is required.\n  at /home/infolis-web/mongoose-jsonld/src/handlers/restful.coffee:113:15\n  at /home/infolis-web/infolis-web/node_modules/mongoose/lib/document.js:1688:19\n  at handleError (/home/infolis-web/infolis-web/node_modules/mongoose/node_modules/hooks-fixed/hooks.js:40:22)\n  at _next (/home/infolis-web/infolis-web/node_modules/mongoose/node_modules/hooks-fixed/hooks.js:46:22)\n  at fnWrapper (/home/infolis-web/infolis-web/node_modules/mongoose/node_modules/hooks-fixed/hooks.js:186:18)\n  at /home/infolis-web/infolis-web/node_modules/mongoose/lib/schema.js:198:13\n  at complete (/home/infolis-web/infolis-web/node_modules/mongoose/lib/document.js:1108:7)\n  at /home/infolis-web/infolis-web/node_modules/mongoose/lib/document.js:1137:20\n  at SchemaString.SchemaType.doValidate (/home/infolis-web/infolis-web/node_modules/mongoose/lib/schematype.js:645:22)\n  at /home/infolis-web/infolis-web/node_modules/mongoose/lib/document.js:1133:9\n  at process._tickCallback (node.js:355:11)\n",
  "message": "ValidationError: Path `status` is required.",
  "cause": {
    "stack": "Error\n  at MongooseError.ValidationError (/home/infolis-web/infolis-web/node_modules/mongoose/lib/error/validation.js:22:16)\n  at model.Document.invalidate (/home/infolis-web/infolis-web/node_modules/mongoose/lib/document.js:1260:32)\n  at /home/infolis-web/infolis-web/node_modules/mongoose/lib/document.js:1135:16\n  at validate (/home/infolis-web/infolis-web/node_modules/mongoose/lib/schematype.js:653:7)\n  at /home/infolis-web/infolis-web/node_modules/mongoose/lib/schematype.js:681:9\n  at Array.forEach (native)\n  at SchemaString.SchemaType.doValidate (/home/infolis-web/infolis-web/node_modules/mongoose/lib/schematype.js:658:19)\n  at /home/infolis-web/infolis-web/node_modules/mongoose/lib/document.js:1133:9\n  at process._tickCallback (node.js:355:11)\n",
    "message": "Execution validation failed",
    "name": "ValidationError",
    "errors": {
      "status": {
        "properties": {
          "type": "required",
          "message": "Path `{PATH}` is required.",
          "path": "status"
        },
        "stack": "Error\n  at MongooseError.ValidatorError (/home/infolis-web/infolis-web/node_modules/mongoose/lib/error/validator.js:25:16)\n  at validate (/home/infolis-web/infolis-web/node_modules/mongoose/lib/schematype.js:652:13)\n  at /home/infolis-web/infolis-web/node_modules/mongoose/lib/schematype.js:681:9\n  at Array.forEach (native)\n  at SchemaString.SchemaType.doValidate (/home/infolis-web/infolis-web/node_modules/mongoose/lib/schematype.js:658:19)\n  at /home/infolis-web/infolis-web/node_modules/mongoose/lib/document.js:1133:9\n  at process._tickCallback (node.js:355:11)\n",
        "message": "Path `status` is required.",
        "name": "ValidatorError",
        "kind": "required",
        "path": "status"
      }
    }
  }
}
```

**Comment by kba** [comment]
> https://github.com/infolis/infolis-web/issues/20#issuecomment-157769629

That is an expected failure. We don't want the API consumers to POST executions with `status` or `log`, that's why we removed that from the execution. However, API consumers should know why their requests failed and this error message explains it.

I think the way to go here is to work on documentation like https://github.com/infolis/infolis-web/wiki/API-calls-to-algorithms and promote the `/api/execute` endpoint.

**Comment by zuphilip** [comment]
Okay, so here the example is then just a hint for a starting point for the user, but it is now a garantued working example. Similar: `post api/infolisFile`.

**Comment by zuphilip** [comment]
The result from the example in `post api/infolisPattern`looks different:

```
{
  "stack": "Error: WriteConcernError(cannot index parallel arrays [tags] [words])\n  at /home/infolis-web/mongoose-jsonld/src/handlers/restful.coffee:113:15\n  at /home/infolis-web/infolis-web/node_modules/mongoose/lib/document.js:1688:19\n  at handleError (/home/infolis-web/infolis-web/node_modules/mongoose/node_modules/hooks-fixed/hooks.js:40:22)\n  at next_ (/home/infolis-web/infolis-web/node_modules/mongoose/node_modules/hooks-fixed/hooks.js:75:26)\n  at fnWrapper (/home/infolis-web/infolis-web/node_modules/mongoose/node_modules/hooks-fixed/hooks.js:186:18)\n  at /home/infolis-web/infolis-web/node_modules/mongoose/lib/model.js:220:15\n  at /home/infolis-web/infolis-web/node_modules/mongoose/lib/model.js:123:9\n  at /home/infolis-web/infolis-web/node_modules/mongoose/node_modules/mongodb/lib/collection.js:448:20\n  at /home/infolis-web/infolis-web/node_modules/mongoose/node_modules/mongodb/lib/collection.js:589:14\n  at /home/infolis-web/infolis-web/node_modules/mongoose/node_modules/mongodb/lib/bulk/unordered.js:457:9\n  at resultHandler (/home/infolis-web/infolis-web/node_modules/mongoose/node_modules/mongodb/lib/bulk/unordered.js:409:5)\n  at /home/infolis-web/infolis-web/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/wireprotocol/2_4_support.js:495:15\n  at [object Object].Callbacks.emit (/home/infolis-web/infolis-web/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:95:3)\n  at [object Object].messageHandler (/home/infolis-web/infolis-web/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:243:23)\n  at Socket.<anonymous> (/home/infolis-web/infolis-web/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:262:22)\n  at Socket.emit (events.js:107:17)\n  at readableAddChunk (_stream_readable.js:163:16)\n  at Socket.Readable.push (_stream_readable.js:126:10)\n  at TCP.onread (net.js:538:20)\n",
  "message": "WriteConcernError(cannot index parallel arrays [tags] [words])",
  "cause": {
    "code": 10088,
    "errmsg": "cannot index parallel arrays [tags] [words]"
  }
}
```

**Comment by kba** [comment]
> https://github.com/infolis/infolis-web/issues/20#issuecomment-157779423

Indeed, that is a bug. We're using MongoDB indexing to speed up queries and there is a limitation that only one array per document may be indexed. Will fix.

**Comment by kba** [comment]
Dropped the index and reindexed, fixed.

**Comment by bolandka** [comment]
Current state:
TagResolver: works
Selecting InfolisFIles: works
SelectingInfolisPatterns: works
AssigningTags: works
FrequencyBasedBoostrapping: works
ApplyPatternAndResolve: does _not_ seem to work, doesn't log
BibliographyExctractor: works
TextExtractor (both calls): work

**Comment by kba** [comment]
This did work, so closing this. Might be a good idea to integrate the examples into our automated tests @infolis/developers
