### ISSUE TITLE
[api/upload] Error content-type missing boundary

### ISSUE THREAD

**Issue by zuphilip** [infolis/infolis-web#36]
The [api/upload](http://infolis.gesis.org/infolink/api#!/essential/post_api_upload) throws an error for every file I try:

```
{
  "stack": "Error: Error: content-type missing boundary\n  at /home/infolis-web/infolis-web/src/routes/upload.coffee:56:21\n  at IncomingMessage.<anonymous> (/home/infolis-web/infolis-web/node_modules/multiparty/index.js:116:9)\n  at IncomingMessage.g (events.js:199:16)\n  at IncomingMessage.emit (events.js:104:17)\n  at _stream_readable.js:908:16\n  at process._tickCallback (node.js:355:11)\n",
  "message": "Error: content-type missing boundary"
}
```

Actually the curl request seems wrong:

```
curl -X POST --header 'Content-Type: multipart/form-data' --header 'Accept: application/json' -d 'file=%5Bobject%20File%5D&mediaType=application%2Fpdf' "http://infolis.gesis.org/infolink/api/upload"
```

**Comment by kba** [comment]
Should be fixed again.

The curl error was related.
