### ISSUE TITLE
ApplyPatternAndResolve Test, Error reading entity from input stream 

### ISSUE THREAD

**Issue by Dommii** [infolis/infolis-web#45]
``` js
{
  "algorithm": "io.github.infolis.algorithm.ApplyPatternAndResolve",
  "inputFiles": [
    "http://infolis.gesis.org/infolink/api/infolisFile/15e2f4f0-8f4c-11e5-9bfb-37e8acc5d407"
  ],
  "patterns": [
    "http://infolis.gesis.org/infolink/api/infolisPattern/d2ec7fc0-8f48-11e5-9bfb-37e8acc5d407"
  ],
  "queryServiceClasses":
    "io.github.infolis.datasetMatcher.DaraHTMLQueryService"
}

results in:

"status": 404,
    "text": "Could not retrieve execution http://infolis.gesis.org/infolink/api/execution/31c72790-8f4c-11e5-9bfb-37e8acc5d407\njavax.ws.rs.ProcessingException: Error reading entity from input stream.
```

**Comment by kba** [comment]
Backend log

```
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.util.ArrayList out of VALUE_STRING token
 at [Source: org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream@366b875c; line: 1, column: 111] (through reference chain: io.github.infolis.model.Execution["queryServiceClasses"])
```

**Comment by kba** [comment]
`queryServiceClasses` Should be an array of strings in the data model.

**Comment by kba** [comment]
Tried again with

``` js
{
  "algorithm": "io.github.infolis.algorithm.ApplyPatternAndResolve",
  "inputFiles": [
    "http://infolis.gesis.org/infolink/api/infolisFile/15e2f4f0-8f4c-11e5-9bfb-37e8acc5d407"
  ],
  "patterns": [
    "http://infolis.gesis.org/infolink/api/infolisPattern/d2ec7fc0-8f48-11e5-9bfb-37e8acc5d407"
  ],
  "status": "PENDING",
  "queryServiceClasses": [
    "io.github.infolis.datasetMatcher.DaraHTMLQueryService"
  ]
}
```

New error on the backend:

```
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Can not construct instance of java.lang.Class, problem: io.github.infolis.datasetMatcher.DaraHTMLQueryService
 at [Source: org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream@297d9878; line: 1, column: 236] (through reference chain: io.github.infolis.model.Execution["queryServiceClasses"])
...
Caused by: java.lang.ClassNotFoundException: io.github.infolis.datasetMatcher.DaraHTMLQueryService
```

**Comment by kba** [comment]
Ah, package is wrong

**Comment by kba** [comment]
``` js
{
  "algorithm": "io.github.infolis.algorithm.ApplyPatternAndResolve",
  "inputFiles": [
    "http://infolis.gesis.org/infolink/api/infolisFile/15e2f4f0-8f4c-11e5-9bfb-37e8acc5d407"
  ],
  "patterns": [
    "http://infolis.gesis.org/infolink/api/infolisPattern/d2ec7fc0-8f48-11e5-9bfb-37e8acc5d407"
  ],
  "status": "PENDING",
  "queryServiceClasses": [
    "io.github.infolis.infolink.datasetMatcher.DaraHTMLQueryService"
  ]
}
```

executes http://infolis.gesis.org/infolink/api/execution/22cec400-8f5b-11e5-aa6e-f70c887c62b5?format=text/turtle and completes as `FINISHED`.

Backend logs:

```
2015-11-20 08:46:13,454 WARN [pool-20-thread-2] i.g.i.u.LimitedTimeMatcher [LimitedTimeMatcher.java:127] Thread '2474.txt
.*?Datenbasis: (\S*?\s?\S+?\s?\S+?\s?\S+?\s?\S*?), eigene Berechnung.*?' took 33480.54214500001 ms, longer than the maximum of 32671 ms, shutting down to avoid pathological backtacking.
Exception in thread "2474.txt
.*?Datenbasis: (\S*?\s?\S+?\s?\S+?\s?\S+?\s?\S*?), eigene Berechnung.*?" 2015-11-20 08:46:13,454 ERROR [pool-20-thread-2] i.g.i.a.RegexSearcher [RegexSearcher.java:86] Search was aborted. TODO
java.lang.RuntimeException: java.lang.InterruptedException
        at io.github.infolis.util.LimitedTimeMatcher$InterruptibleCharSequence.charAt(LimitedTimeMatcher.java:43)
        at java.lang.Character.codePointAt(Character.java:4668)
        at java.util.regex.Pattern$CharProperty.match(Pattern.java:3693)
```

**Comment by kba** [comment]
See https://github.com/infolis/infoLink/issues/45 and https://github.com/infolis/infoLink/pull/46.

**Comment by kba** [comment]
For completeness, a working example is now 

``` js
{
  "algorithm": "io.github.infolis.algorithm.ApplyPatternAndResolve",
  "inputFiles": [
    "http://infolis.gesis.org/infolink/api/infolisFile/15e2f4f0-8f4c-11e5-9bfb-37e8acc5d407"
  ],
  "patterns": [
    "http://infolis.gesis.org/infolink/api/infolisPattern/d2ec7fc0-8f48-11e5-9bfb-37e8acc5d407"
  ],
  "queryServiceClasses": [
    "io.github.infolis.resolve.DaraHTMLQueryService"
  ]
}
```

**Comment by zuphilip** [comment]
Should the `status` really be specified on input?

**Comment by zuphilip** [comment]
That is different from https://github.com/infolis/infolis-web/wiki/API-calls-to-algorithms#applypatternandresolve

**Comment by kba** [comment]
> Should the status really be specified on input?
> No. Using `/api/execute` won't set it.
> 
> That is different from https://github.com/infolis/infolis-web/wiki/API-calls-to-algorithms#applypatternandresolve

I tried to make @Dommii example work. Maybe she can give a seminal (i.e. working) example?
