### ISSUE TITLE
Error in FrequencyBasedBootstrapping: problem with index

### ISSUE THREAD

**Issue by bolandka** [infolis/infolis-web#52]
part of https://github.com/infolis/infolis-web/issues/20

http://infolis.gesis.org/infolink/api/execution/8c5c4720-8ff7-11e5-a54f-3fc06a1d5c6e

to reproduce, use Assigning Tags api call: https://github.com/infolis/infolis-web/wiki/API-calls-to-algorithms#assigning-tags

**Comment by bolandka** [comment]
now the same call works o_O

**Comment by kba** [comment]
Log shows:

```
2015-11-21 03:24:00,032 ERROR [pool-2-thread-2] i.g.i.a.Indexer [BaseAlgorithm.java:145] Could not retrieve file http://infolis.gesis.org/infolink/api/infolisFile/ac472af0-8df4-11e5-99dc-bdf72f9f3c6f: javax.ws.rs.ProcessingException: Error closing message content input stream.
```

and then 

```
2015-11-21 03:24:00,138 ERROR [pool-2-thread-2] i.g.i.a.BaseAlgorithm [BaseAlgorithm.java:145] Execution threw an Exception: org.apache.lucene.index.IndexNotFoundException: no segments* file found in org.apache.lucene.store.MMapDirectory@/tmp/infolis/infolis-index-4732785342263994189 lockFactory=org.apache.lucene.store.NativeFSLockFactory@f2d9ce9: files: []
org.apache.lucene.index.IndexNotFoundException: no segments* file found in org.apache.lucene.store.MMapDirectory@/tmp/infolis/infolis-index-4732785342263994189 lockFactory=org.apache.lucene.store.NativeFSLockFactory@f2d9ce9: files: []
        at org.apache.lucene.index.SegmentInfos$FindSegmentsFile.run(SegmentInfos.java:712)
        at org.apache.lucene.index.DirectoryReader.open(DirectoryReader.java:75)
        at org.apache.lucene.index.IndexReader.open(IndexReader.java:462)
        at org.apache.lucene.index.IndexReader.open(IndexReader.java:308)
        at io.github.infolis.algorithm.SearchTermPosition.execute(SearchTermPosition.java:79)
        at io.github.infolis.algorithm.BaseAlgorithm.run(BaseAlgorithm.java:183)
        at io.github.infolis.algorithm.Bootstrapping.getContextsForSeed(Bootstrapping.java:82)
        at io.github.infolis.algorithm.FrequencyBasedBootstrapping.bootstrap(FrequencyBasedBootstrapping.java:106)
        at io.github.infolis.algorithm.Bootstrapping.execute(Bootstrapping.java:176)
        at io.github.infolis.algorithm.BaseAlgorithm.run(BaseAlgorithm.java:183)
        at io.github.infolis.scheduler.ExecutionScheduler$1.run(ExecutionScheduler.java:60)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by kba** [comment]
I guess this was just bad timing, the frontend was unavailable right at the request for the file. This cascaded into the file description not being loaded etc.
